import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Solvix',
  description: 'Generated by create next app',
  icons: {
    icon: '/FullLogo_Transparent_NoBuffer.png',
  },
  openGraph: {
    images: [
      {
        url: '/FullLogo_Transparent_NoBuffer.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: '/FullLogo_Transparent_NoBuffer.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
